/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-27 07:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Index</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container py-5 h-100\">\r\n");
      out.write("    <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("      <div class=\"col-12\">\r\n");
      out.write("        <div class=\"card card-registration card-registration-2\" style=\"border-radius: 15px;\">\r\n");
      out.write("          <div class=\"card-body p-0\">\r\n");
      out.write("            <div class=\"row g-0\">\r\n");
      out.write("              <div class=\"col-lg-8\">\r\n");
      out.write("                <div class=\"p-5\">\r\n");
      out.write("                  <div class=\"d-flex justify-content-between align-items-center mb-5\">\r\n");
      out.write("                    <h1 class=\"fw-bold mb-0 text-black\">Shopping Cart</h1>\r\n");
      out.write("                    <h6 class=\"mb-0 text-muted\">3 items</h6>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row mb-4 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img5.webp\"\r\n");
      out.write("                        class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                      <h6 class=\"text-muted\">Shirt</h6>\r\n");
      out.write("                      <h6 class=\"text-black mb-0\">Cotton T-shirt</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                      <button class=\"btn btn-link px-2\"\r\n");
      out.write("                        onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                        <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("\r\n");
      out.write("                      <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"1\" type=\"number\"\r\n");
      out.write("                        class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                      <button class=\"btn btn-link px-2\"\r\n");
      out.write("                        onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                      <h6 class=\"mb-0\">€ 44.00</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                      <a href=\"#!\" class=\"text-muted\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row mb-4 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img6.webp\"\r\n");
      out.write("                        class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                      <h6 class=\"text-muted\">Shirt</h6>\r\n");
      out.write("                      <h6 class=\"text-black mb-0\">Cotton T-shirt</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                      <button class=\"btn btn-link px-2\"\r\n");
      out.write("                        onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                        <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("\r\n");
      out.write("                      <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"1\" type=\"number\"\r\n");
      out.write("                        class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                      <button class=\"btn btn-link px-2\"\r\n");
      out.write("                        onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                      <h6 class=\"mb-0\">€ 44.00</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                      <a href=\"#!\" class=\"text-muted\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row mb-4 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img7.webp\"\r\n");
      out.write("                        class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                      <h6 class=\"text-muted\">Shirt</h6>\r\n");
      out.write("                      <h6 class=\"text-black mb-0\">Cotton T-shirt</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                      <button class=\"btn btn-link px-2\"\r\n");
      out.write("                        onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                        <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("\r\n");
      out.write("                      <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"1\" type=\"number\"\r\n");
      out.write("                        class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                      <button class=\"btn btn-link px-2\"\r\n");
      out.write("                        onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                      </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                      <h6 class=\"mb-0\">€ 44.00</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                      <a href=\"#!\" class=\"text-muted\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"pt-5\">\r\n");
      out.write("                    <h6 class=\"mb-0\"><a href=\"#!\" class=\"text-body\"><i\r\n");
      out.write("                          class=\"fas fa-long-arrow-alt-left me-2\"></i>Back to shop</a></h6>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-4 bg-grey\">\r\n");
      out.write("                <div class=\"p-5\">\r\n");
      out.write("                  <h3 class=\"fw-bold mb-5 mt-2 pt-1\">Summary</h3>\r\n");
      out.write("                  <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"d-flex justify-content-between mb-4\">\r\n");
      out.write("                    <h5 class=\"text-uppercase\">items 3</h5>\r\n");
      out.write("                    <h5>€ 132.00</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <h5 class=\"text-uppercase mb-3\">Shipping</h5>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"mb-4 pb-2\">\r\n");
      out.write("                    <select class=\"select\">\r\n");
      out.write("                      <option value=\"1\">Standard-Delivery- €5.00</option>\r\n");
      out.write("                      <option value=\"2\">Two</option>\r\n");
      out.write("                      <option value=\"3\">Three</option>\r\n");
      out.write("                      <option value=\"4\">Four</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <h5 class=\"text-uppercase mb-3\">Give code</h5>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"mb-5\">\r\n");
      out.write("                    <div class=\"form-outline\">\r\n");
      out.write("                      <input type=\"text\" id=\"form3Examplea2\" class=\"form-control form-control-lg\" />\r\n");
      out.write("                      <label class=\"form-label\" for=\"form3Examplea2\">Enter your code</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"d-flex justify-content-between mb-5\">\r\n");
      out.write("                    <h5 class=\"text-uppercase\">Total price</h5>\r\n");
      out.write("                    <h5>€ 137.00</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-dark btn-block btn-lg\"\r\n");
      out.write("                    data-mdb-ripple-color=\"dark\">Register</button>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
